export type ICurrencyConfig = {
  code: string;
  symbol: string;
  locale: string;
};

export type ICountry = {
  countryName: string;
  currency: ICurrencyConfig;
};

// 120+ country list — can be extended. Locales chosen to reflect common formatting.
export const countries: ICountry[] = [
  { countryName: "United States", currency: { code: "USD", symbol: "$", locale: "en-US" } },
  { countryName: "United Kingdom", currency: { code: "GBP", symbol: "£", locale: "en-GB" } },
  { countryName: "European Union", currency: { code: "EUR", symbol: "€", locale: "de-DE" } },
  { countryName: "Germany", currency: { code: "EUR", symbol: "€", locale: "de-DE" } },
  { countryName: "France", currency: { code: "EUR", symbol: "€", locale: "fr-FR" } },
  { countryName: "Spain", currency: { code: "EUR", symbol: "€", locale: "es-ES" } },
  { countryName: "Italy", currency: { code: "EUR", symbol: "€", locale: "it-IT" } },
  { countryName: "Netherlands", currency: { code: "EUR", symbol: "€", locale: "nl-NL" } },
  { countryName: "Belgium", currency: { code: "EUR", symbol: "€", locale: "fr-BE" } },
  { countryName: "Austria", currency: { code: "EUR", symbol: "€", locale: "de-AT" } },
  { countryName: "Ireland", currency: { code: "EUR", symbol: "€", locale: "en-IE" } },
  { countryName: "Portugal", currency: { code: "EUR", symbol: "€", locale: "pt-PT" } },
  { countryName: "Greece", currency: { code: "EUR", symbol: "€", locale: "el-GR" } },
  { countryName: "Poland", currency: { code: "PLN", symbol: "zł", locale: "pl-PL" } },
  { countryName: "Czech Republic", currency: { code: "CZK", symbol: "Kč", locale: "cs-CZ" } },
  { countryName: "Sweden", currency: { code: "SEK", symbol: "kr", locale: "sv-SE" } },
  { countryName: "Norway", currency: { code: "NOK", symbol: "kr", locale: "nb-NO" } },
  { countryName: "Denmark", currency: { code: "DKK", symbol: "kr", locale: "da-DK" } },
  { countryName: "Switzerland", currency: { code: "CHF", symbol: "CHF", locale: "de-CH" } },
  { countryName: "Finland", currency: { code: "EUR", symbol: "€", locale: "fi-FI" } },
  { countryName: "Iceland", currency: { code: "ISK", symbol: "kr", locale: "is-IS" } },
  { countryName: "Australia", currency: { code: "AUD", symbol: "A$", locale: "en-AU" } },
  { countryName: "New Zealand", currency: { code: "NZD", symbol: "$", locale: "en-NZ" } },
  { countryName: "Canada", currency: { code: "CAD", symbol: "$", locale: "en-CA" } },
  { countryName: "Mexico", currency: { code: "MXN", symbol: "$", locale: "es-MX" } },
  { countryName: "Brazil", currency: { code: "BRL", symbol: "R$", locale: "pt-BR" } },
  { countryName: "Argentina", currency: { code: "ARS", symbol: "$", locale: "es-AR" } },
  { countryName: "Chile", currency: { code: "CLP", symbol: "$", locale: "es-CL" } },
  { countryName: "Colombia", currency: { code: "COP", symbol: "$", locale: "es-CO" } },
  { countryName: "Peru", currency: { code: "PEN", symbol: "S/", locale: "es-PE" } },
  { countryName: "Venezuela", currency: { code: "VES", symbol: "Bs.", locale: "es-VE" } },
  { countryName: "South Africa", currency: { code: "ZAR", symbol: "R", locale: "en-ZA" } },
  { countryName: "Nigeria", currency: { code: "NGN", symbol: "₦", locale: "en-NG" } },
  { countryName: "Egypt", currency: { code: "EGP", symbol: "£", locale: "ar-EG" } },
  { countryName: "Kenya", currency: { code: "KES", symbol: "KSh", locale: "en-KE" } },
  { countryName: "Morocco", currency: { code: "MAD", symbol: "DH", locale: "fr-MA" } },
  { countryName: "Turkey", currency: { code: "TRY", symbol: "₺", locale: "tr-TR" } },
  { countryName: "Russia", currency: { code: "RUB", symbol: "₽", locale: "ru-RU" } },
  { countryName: "Saudi Arabia", currency: { code: "SAR", symbol: "﷼", locale: "ar-SA" } },
  { countryName: "United Arab Emirates", currency: { code: "AED", symbol: "د.إ", locale: "ar-AE" } },
  { countryName: "Israel", currency: { code: "ILS", symbol: "₪", locale: "he-IL" } },
  { countryName: "India", currency: { code: "INR", symbol: "₹", locale: "en-IN" } },
  { countryName: "Pakistan", currency: { code: "PKR", symbol: "₨", locale: "en-PK" } },
  { countryName: "Bangladesh", currency: { code: "BDT", symbol: "৳", locale: "bn-BD" } },
  { countryName: "Sri Lanka", currency: { code: "LKR", symbol: "Rs", locale: "en-LK" } },
  { countryName: "Nepal", currency: { code: "NPR", symbol: "₨", locale: "ne-NP" } },
  { countryName: "Bhutan", currency: { code: "BTN", symbol: "Nu.", locale: "en-BT" } },
  { countryName: "Maldives", currency: { code: "MVR", symbol: "Rf", locale: "en-MV" } },
  { countryName: "China", currency: { code: "CNY", symbol: "¥", locale: "zh-CN" } },
  { countryName: "Hong Kong", currency: { code: "HKD", symbol: "$", locale: "zh-HK" } },
  { countryName: "Macau", currency: { code: "MOP", symbol: "MOP$", locale: "pt-MO" } },
  { countryName: "Japan", currency: { code: "JPY", symbol: "¥", locale: "ja-JP" } },
  { countryName: "South Korea", currency: { code: "KRW", symbol: "₩", locale: "ko-KR" } },
  { countryName: "North Korea", currency: { code: "KPW", symbol: "₩", locale: "ko-KP" } },
  { countryName: "Taiwan", currency: { code: "TWD", symbol: "NT$", locale: "zh-TW" } },
  { countryName: "Philippines", currency: { code: "PHP", symbol: "₱", locale: "en-PH" } },
  { countryName: "Indonesia", currency: { code: "IDR", symbol: "Rp", locale: "id-ID" } },
  { countryName: "Malaysia", currency: { code: "MYR", symbol: "RM", locale: "ms-MY" } },
  { countryName: "Singapore", currency: { code: "SGD", symbol: "$", locale: "en-SG" } },
  { countryName: "Thailand", currency: { code: "THB", symbol: "฿", locale: "th-TH" } },
  { countryName: "Vietnam", currency: { code: "VND", symbol: "₫", locale: "vi-VN" } },
  { countryName: "Cambodia", currency: { code: "KHR", symbol: "៛", locale: "km-KH" } },
  { countryName: "Laos", currency: { code: "LAK", symbol: "₭", locale: "lo-LA" } },
  { countryName: "Myanmar", currency: { code: "MMK", symbol: "Ks", locale: "my-MM" } },
  { countryName: "Brunei", currency: { code: "BND", symbol: "$", locale: "en-BN" } },
  { countryName: "Timor-Leste", currency: { code: "USD", symbol: "$", locale: "pt-TL" } },
  { countryName: "Fiji", currency: { code: "FJD", symbol: "$", locale: "en-FJ" } },
  { countryName: "Papua New Guinea", currency: { code: "PGK", symbol: "K", locale: "en-PG" } },
  { countryName: "Solomon Islands", currency: { code: "SBD", symbol: "$", locale: "en-SB" } },
  { countryName: "Samoa", currency: { code: "WST", symbol: "WS$", locale: "sm-WS" } },
  { countryName: "Tonga", currency: { code: "TOP", symbol: "T$", locale: "en-TO" } },
  { countryName: "Vanuatu", currency: { code: "VUV", symbol: "VT", locale: "bi-VU" } },
  { countryName: "Kiribati", currency: { code: "AUD", symbol: "A$", locale: "en-KI" } },
  { countryName: "Nauru", currency: { code: "AUD", symbol: "A$", locale: "en-NR" } },
  { countryName: "Tuvalu", currency: { code: "AUD", symbol: "A$", locale: "en-TV" } },
  { countryName: "Russia (Kaliningrad)", currency: { code: "RUB", symbol: "₽", locale: "ru-RU" } },
  { countryName: "Ukraine", currency: { code: "UAH", symbol: "₴", locale: "uk-UA" } },
  { countryName: "Belarus", currency: { code: "BYN", symbol: "Br", locale: "be-BY" } },
  { countryName: "Romania", currency: { code: "RON", symbol: "lei", locale: "ro-RO" } },
  { countryName: "Bulgaria", currency: { code: "BGN", symbol: "лв", locale: "bg-BG" } },
  { countryName: "Hungary", currency: { code: "HUF", symbol: "Ft", locale: "hu-HU" } },
  { countryName: "Slovakia", currency: { code: "EUR", symbol: "€", locale: "sk-SK" } },
  { countryName: "Slovenia", currency: { code: "EUR", symbol: "€", locale: "sl-SI" } },
  { countryName: "Croatia", currency: { code: "HRK", symbol: "kn", locale: "hr-HR" } },
  { countryName: "Serbia", currency: { code: "RSD", symbol: "дин", locale: "sr-RS" } },
  { countryName: "Bosnia and Herzegovina", currency: { code: "BAM", symbol: "KM", locale: "bs-BA" } },
  { countryName: "North Macedonia", currency: { code: "MKD", symbol: "ден", locale: "mk-MK" } },
  { countryName: "Albania", currency: { code: "ALL", symbol: "L", locale: "sq-AL" } },
  { countryName: "Montenegro", currency: { code: "EUR", symbol: "€", locale: "sr-ME" } },
  { countryName: "Luxembourg", currency: { code: "EUR", symbol: "€", locale: "fr-LU" } },
  { countryName: "Malta", currency: { code: "EUR", symbol: "€", locale: "en-MT" } },
  { countryName: "Cyprus", currency: { code: "EUR", symbol: "€", locale: "el-CY" } },
  { countryName: "Estonia", currency: { code: "EUR", symbol: "€", locale: "et-EE" } },
  { countryName: "Latvia", currency: { code: "EUR", symbol: "€", locale: "lv-LV" } },
  { countryName: "Lithuania", currency: { code: "EUR", symbol: "€", locale: "lt-LT" } },
  { countryName: "Turkey (TR)", currency: { code: "TRY", symbol: "₺", locale: "tr-TR" } },
  { countryName: "Kazakhstan", currency: { code: "KZT", symbol: "₸", locale: "kk-KZ" } },
  { countryName: "Uzbekistan", currency: { code: "UZS", symbol: "so'm", locale: "uz-UZ" } },
  { countryName: "Azerbaijan", currency: { code: "AZN", symbol: "₼", locale: "az-AZ" } },
  { countryName: "Georgia", currency: { code: "GEL", symbol: "₾", locale: "ka-GE" } },
  { countryName: "Armenia", currency: { code: "AMD", symbol: "֏", locale: "hy-AM" } },
  { countryName: "Iran", currency: { code: "IRR", symbol: "﷼", locale: "fa-IR" } },
  { countryName: "Iraq", currency: { code: "IQD", symbol: "ع.د", locale: "ar-IQ" } },
  { countryName: "Afghanistan", currency: { code: "AFN", symbol: "؋", locale: "ps-AF" } },
  { countryName: "Tunisia", currency: { code: "TND", symbol: "د.ت", locale: "ar-TN" } },
  { countryName: "Algeria", currency: { code: "DZD", symbol: "د.ج", locale: "ar-DZ" } },
  { countryName: "Ethiopia", currency: { code: "ETB", symbol: "Br", locale: "am-ET" } },
  { countryName: "Uganda", currency: { code: "UGX", symbol: "UGX", locale: "en-UG" } },
  { countryName: "Tanzania", currency: { code: "TZS", symbol: "TSh", locale: "en-TZ" } },
  { countryName: "Sudan", currency: { code: "SDG", symbol: "SDG", locale: "ar-SD" } },
  { countryName: "Mozambique", currency: { code: "MZN", symbol: "MT", locale: "pt-MZ" } },
  { countryName: "Angola", currency: { code: "AOA", symbol: "Kz", locale: "pt-AO" } },
  { countryName: "Zimbabwe", currency: { code: "ZWL", symbol: "$", locale: "en-ZW" } },
  { countryName: "Honduras", currency: { code: "HNL", symbol: "L", locale: "es-HN" } },
  { countryName: "Costa Rica", currency: { code: "CRC", symbol: "₡", locale: "es-CR" } },
  { countryName: "Panama", currency: { code: "PAB", symbol: "B/.", locale: "es-PA" } },
  { countryName: "Dominican Republic", currency: { code: "DOP", symbol: "RD$", locale: "es-DO" } },
  { countryName: "Puerto Rico", currency: { code: "USD", symbol: "$", locale: "es-PR" } },
  { countryName: "Guatemala", currency: { code: "GTQ", symbol: "Q", locale: "es-GT" } },
  { countryName: "El Salvador", currency: { code: "USD", symbol: "$", locale: "es-SV" } },
  { countryName: "Nicaragua", currency: { code: "NIO", symbol: "C$", locale: "es-NI" } },
  { countryName: "Belize", currency: { code: "BZD", symbol: "$", locale: "en-BZ" } },
  { countryName: "Paraguay", currency: { code: "PYG", symbol: "₲", locale: "es-PY" } },
  { countryName: "Uruguay", currency: { code: "UYU", symbol: "$U", locale: "es-UY" } },
  { countryName: "Bolivia", currency: { code: "BOB", symbol: "Bs.", locale: "es-BO" } },
  { countryName: "Suriname", currency: { code: "SRD", symbol: "$", locale: "nl-SR" } },
  { countryName: "Guyana", currency: { code: "GYD", symbol: "$", locale: "en-GY" } },
  { countryName: "Iceland (re)", currency: { code: "ISK", symbol: "kr", locale: "is-IS" } },
];

export const defaultCountry: ICountry = countries.find((c) => c.countryName === "European Union") || countries[0];
